# ???? ?????? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/otp_db
spring.datasource.username=postgres
spring.datasource.password=sql
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? ??????????? (????????? ???????? ????????)
logging.level.org.springframework.web=INFO
logging.level.com.promoit.otp=DEBUG
logging.file.name=logs/otp-service.log

# JWT ????????? ????
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a75d1f87c46990538c7b50b2a75d1f87
jwt.expirationMs=3600000

# Telegram Bot
telegram.bot.token=????? ????
telegram.chat.id=??? id

# ??????????? Spring
spring.task.scheduling.pool.size=1
spring.sql.init.mode=always